sudo: required
services: 
  - docker

before_install:
  - docker build -t codergogoi/react_cicd -f Dockerfile.dev .

script:
  - docker run -e CI=true codergogoi/react_cicd npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  edge: true
  region: ap-south-1
  app: react_cicd
  env: "ReactCicd-env"
  bucket_name: "elasticbeanstalk-ap-south-1-479812415175"
  bucket_path: "react_cicd"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
 